### ISSUE TITLE
NettyClient 重试疑问

### ISSUE THREAD

**Issue by yanglongyu** [marquisXuan/netty#3]
public void start() {
        LOGGER.info("{} -> [启动连接] {}:{}", this.getClass().getName(), url, port);
        bootstrap.handler(new NettyClientHandler());
        ChannelFuture f = bootstrap.connect(url, port);
        try {
            f.channel().closeFuture().sync();
        } catch (InterruptedException e) {
            retry++;
            if (retry > MAX_RETRY_TIMES) {
                throw new RuntimeException("调用Wrong");
            } else {
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e1) {
                    e1.printStackTrace();
                }
                LOGGER.info("第{}次尝试....失败", retry);
                start();
            }
        }
    }
}

 bootstrap.connect(url, port); 这里是异步执行，要是出现异常，你没有catch 住，无法进行重试，我理解的重试应该是重试链接，你这个catch 的是 关闭方法，重试意义不大

**Comment by marquisXuan** [comment]
感谢提出疑问~
这里做的是断线重连~莫名的断开了才去触发重新连接.
如果第一次服务启动就连接不上,那不是说明 ip.port 有问题或者服务端没响应么~
初次连接失败不用记录在断线重连次数里~是这么个想法哟~

**Comment by marquisXuan** [comment]
> 感谢提出疑问~
这里做的是断线重连
莫名的断开了才去触发重新连接.
如果第一次服务启动就连接不上,那不是说明 ip.port 有问题或者服务端没响应么
初次连接失败不用记录在断线重连次数里是这么个想法哟 @yanglongyu
